config/routes.rb
Rails.application.routes.draw do
  
  get 'cadastro', :to => 'floriculturas#new'
  get 'login', :to => 'sessions#new'
  get 'logout', :to => 'sessions#destroy'
  get 'venda', :to => 'chamados#new'
  post 'aceitar', :to => 'floriculturas#aceitar'
  post 'recusar', :to => 'floriculturas#recusar'
  
  resources :floriculturas
  resources :usuarios
  resources :sessions  
  resources :chamados  
  
  root 'sessions#new'
  
  
end

app/models/bairro.rb
class Bairro < ActiveRecord::Base
  has_many :floriculturas
end

app/models/chamado.rb
class Chamado < ActiveRecord::Base  
  has_one :floricultura
  has_many :produtos
  
  #Algoritmo de seleção de floricultura
  def selecionaFloricultura
    #Extrai array de objetos pelo select
    @floriculturas = Floricultura.where(:subprefeitura => self.subprefeitura, :posicao => 1)
    
     #movemos as floriculturas
    @floriculturasms = Floricultura.where(:subprefeitura => self.subprefeitura)
    @floriculturasms.each do |i|            
        if(i.posicao == 1)
          i.update_attribute(:posicao, @floriculturasms.length)
        else
          i.update_attribute(:posicao, i.posicao-1)
        end      
    end
    #terminamos de mover as floriculturas
    
    #Selecionamos a primeira posição (first) e depois selecionamos o ID
    id_floricultura = @floriculturas.first.id    
    
    return id_floricultura
  end  
end

app/models/floricultura.rb
class Floricultura < ActiveRecord::Base
  has_one :usuario
  has_many :chamados
 end

app/models/produto.rb
class Produto < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_one :floricultura
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
private
  
  def current_user
    @current_user ||= Usuario.find(session[:usuario_id]) if session[:usuario_id]
  end
  helper_method :current_user
  
  def authorize
    redirect_to login_url, alert: "Você precisa estar logado." if current_user.nil?
  end
  
end

app/controllers/chamados_controller.rb
class ChamadosController < ApplicationController
 before_filter :authorize, only: [:new]
  def index
    @chamados = Chamado.all
  end
  
  def show
    @chamado = Chamado.find(params[:id])
  end
  
  def new
    @chamado = Chamado.new
    @bairro = Bairro.all
    @produto = Produto.all
  end
  
  def create
    #Cria o chamado com os dados entrados no formulario, exceto a floricultura que será escolhida a seguir
    @chamado = Chamado.new(params.require(:chamado).permit(:itens, :total, :nomec, :cpf, :telefone1, :telefone2, :nomef, :endvel, :subprefeitura, :datahorariovel, :nomee, :formapag, :floricultura_escolhida))
    
    #Seleciona a floricultura que será associada ao chamado
    floricultura = @chamado.selecionaFloricultura
    
    #Dá update no objeto chamado
    @chamado.update_attribute(:floricultura_escolhida, floricultura)
    
    if @chamado.save
      redirect_to @chamado
    else
      render 'new'
    end    
  end
end

app/controllers/floriculturas_controller.rb
class FloriculturasController < ApplicationController
  
  def new
    @floricultura = Floricultura.new
    @usuario = Usuario.new
    @bairro = Bairro.all
  end
  
  def create 
    @bairro = Bairro.all
    @floricultura = Floricultura.new(params.require(:floricultura).permit(:email, :nomefloricultura, :endfloricultura, :subprefeitura))
    @usuario = Usuario.new(params.require(:usuario).permit(:password, :password_confirmation))
    @usuario.email = @floricultura.email
    @usuario.tipo = "floricultura"    
    
    if @floricultura.save && @usuario.save
      redirect_to @floricultura
    else
      render 'new'
    end
  end
  
  def show
    @floricultura = Floricultura.find(params[:id])
    @abertos = Chamado.where(:floricultura_escolhida => @floricultura.id, :status => "Aberto")
  end
  
  def aceitar
    @chamado = Chamado.find(params[:chamado])
    @chamado.update_attribute(:status, "Fechado")
    @floricultura = Floricultura.find(params[:id])
    redirect_to @floricultura
  end
  
  def recusar
    @chamado = Chamado.find(params[:chamado])
    prox_floricultura = @chamado.selecionaFloricultura
    @chamado.update_attribute(:floricultura_escolhida, prox_floricultura)
    
    @floricultura = Floricultura.find(params[:id])
    redirect_to @floricultura
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    usuario = Usuario.find_by_email(params[:email])
    floricultura = Floricultura.find_by_email(params[:email])
    if usuario && usuario.authenticate(params[:password])
      session[:usuario_id] = usuario.id
      
      if usuario.tipo == "agenciador"
        redirect_to venda_url
      else         
        redirect_to floricultura 
      end      
           
    else
      flash.now.alert = "Email ou senha incorretos."
      render "new"
    end
  end

  def destroy
    session[:usuario_id] = nil
    redirect_to root_url
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def new
    @usuario = Usuario.new
  end
  
  def create
    @usuario = Usuario.new(params.require(:usuario).permit(:email, :password, :password_confirmation, :tipo))
         
    if @usuario.save
      redirect_to root_url
    else
      render 'new'
    end
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bairro_helper.rb
module BairroHelper
end

app/helpers/chamados_helper.rb
module ChamadosHelper
end

app/helpers/floriculturas_helper.rb
module FloriculturasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuario_helper.rb
module UsuarioHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chamados/_cadastro_dados.html.erb
<div class="container_secao" id="cadastro_dados">
	<h1>2. Preencha os dados</h1>
	<fieldset>
		<h2>Dados do Contratante</h2>
		<p>
			campos sinalizados com * são obrigatórios
		</p>
		<table class="alinhar">
			<tr>
				<td><strong>Nome Completo (Contratante) *</strong></td>
				<td> <%= f.text_field :nomec, :required => true %> </td>
			</tr>
			<tr>
				<td><strong>CPF (Contratante) *</strong></td>
				<td> <%= f.text_field :cpf, :required => true, :pattern => "^[0-9]{11}$", :title => "Você deve digitar um CPF válido de 11 digítos" %> </td>
			</tr>
			<tr>
				<td><strong>Telefone 1 *</strong></td>
				<td> <%= f.text_field :telefone1, :required => true, :pattern => "^[0-9]{10,}$", :title => "Você deve digitar um telefone válido com o DDD. Exemplo: 11987654321"  %> </td>
			</tr>
			<tr>
				<td><strong>Telefone 2</strong></td>
				<td> <%= f.text_field :telefone2, :pattern => "^[0-9]{10,}", :title => "Você deve digitar um telefone válido com o DDD. Exemplo: 11987654321"  %> </td>
			</tr>
		</table>

		<h2>Dados do Falecido e do Velório</h2>
		<table class="alinhar">
			<tr>
				<td><strong>Nome Completo (Falecido) *</strong></td>
				<td> <%= f.text_field :nomef, :required => true  %> </td>
			</tr>
			<tr>
				<td><strong>Endereço do Velório *</strong></td>
				<td> <%= f.text_field :endvel, :required => true  %> </td>
			</tr>
			<tr>
				<td><strong>Bairro *</strong></td>
				<td> <%= f.select :subprefeitura, options_for_select(@bairro.collect { |bairro|
				[bairro.bairro, bairro.subprefeitura] } ), :required => true  %> </td>
			</tr>
			<tr>
				<td><strong>Data e Horário do Velório *</strong></td>
				<td> <%= f.datetime_select :datahorariovel, :required => true  %> </td>
			</tr>
		</table>

		<h2>Dados do Emitente</h2>
		<table class="alinhar">
			<tr>
				<td><strong>Nome Completo (Emitente) *</strong></td>
				<td> <%= f.text_field :nomee, :required => true  %> </td>
			</tr>
			<tr>
				<td><strong>Forma de Pagamento *</strong></td>
				<td> <%= f.select :formapag, ['Crédito', 'Débito', 'Dinheiro', 'Convênio'], :required => true  %> </td>
			</tr>
		</table>
	</fieldset>
	<a href="#confirmacao_floricultura" onclick='confirmaForm()'>
	<button class="big_button">
		Continuar
	</button></a>

</div>

app/views/chamados/_confirmacao_dados.html.erb
<div  class="container_secao" id="confirmacao_floricultura">
	<h1>3. Confirme os dados abaixo</h1>
	<fieldset>
		<h2>Produtos selecionados</h2>
		<% @produto.each do |produto| %>
		<span id='moldura_<%= produto.id %>'> <strong><%= produto.nomeproduto %>:</strong> <span id='confere_<%= produto.id %>'></span><a href="#selecao_flores"> (Editar)</a>
			<br>
		</span>
		<% end %>
		<h3>Total: <span id="confere_qtd_total"></span></h3>
		<h2>Dados do Contratante</h2>
		<table class="alinhar">
			<tr>
				<td><strong>Nome Completo (Contratante):</strong></td>
				<td><span id='c_nomec'></span><a href="#cadastro_dados"> (Editar)</a></td>
			</tr>
			<tr>
				<td><strong>CPF:</strong></td>
				<td><span id='c_cpf'></span><a href="#cadastro_dados"> (Editar)</a></td>
			</tr>
			<tr>
				<td><strong>Telefone 1:</strong></td>
				<td><span id='c_telefone1'></span><a href="#cadastro_dados"> (Editar)</a></td>
			</tr>
			<tr>
				<td><strong>Telefone 2:</strong></td>
				<td><span id='c_telefone2'></span><a href="#cadastro_dados"> (Editar)</a></td>
			</tr>
		</table>

		<h2>Dados do Falecido e do Velório</h2>
		<table class="alinhar">
			<tr>
				<td><strong>Nome Completo (Falecido):</strong></td>
				<td><span id='c_nomef'></span><a href="#cadastro_dados"> (Editar)</a></td>
			</tr>
			<tr>
				<td><strong>Endereço do Velório:</strong></td>
				<td><span id='c_endvel'></span><a href="#cadastro_dados"> (Editar)</a></td>
			</tr>
			<tr>
				<td><strong>Bairro:</strong></td>
				<td><span id='c_bairro'></span><a href="#cadastro_dados"> (Editar)</a></td>
			</tr>
			<tr>
				<td><strong>Data e Horário do Velório:</strong></td>
				<td><span id='c_datahorariovel'></span><a href="#cadastro_dados"> (Editar)</a></td>
			</tr>
		</table>

		<h2>Dados do Emitente</h2>
		<table class="alinhar">
			<tr>
				<td><strong>Nome Completo (Emitente):</strong></td>
				<td><span id='c_nomee'></span><a href="#cadastro_dados"> (Editar)</a></td>
			</tr>
			<tr>
				<td><strong>Forma de Pagamento:</strong></td>
				<td><span id='c_formapag'></span><a href="#cadastro_dados"> (Editar)</a></td>
			</tr>
		</table>
	</fieldset>
	<input id="chamado_total" name="chamado[total]" type="hidden" />
	<input id="chamado_itens" name="chamado[itens]" type="hidden" />
	<%= f.submit 'Finalizar', :class => 'big_button' %>
</div>

app/views/chamados/_selecao_produtos.html.erb
<div class="container_secao" id="selecao_flores">
	<h1>1. Selecione seus produtos</h1>
	<div id="lista_produtos">
		<% @produto.each do |produto| %>
		<div class="moldura_produtos" id='box_<%= produto.id %>'>
			<h3><%= produto.nomeproduto %></h3>
			<h3>R$<%= produto.precoproduto %></h3>
			<%= image_tag produto.imgproduto, size: "200x200" %>
			<p>
				<%= produto.descproduto %>
			</p>
			Quantidade:
			<br />
			<input class="check_produtos" id='qtd_<%= produto.id %>' type="text" value="0" maxlength="2" pattern="/^d${1,}/" />
			<input type="hidden" id='preco_<%= produto.id %>' value='<%= produto.precoproduto %>'>
			<input type="hidden" id='nome_<%= produto.id %>' value='<%= produto.nomeproduto %>'>
		</div>
		<% end %>
	</div>
	<div style="clear:both">
		<h3>Total: <span id="qtd_total"></span><a href="#" onclick="calculaTotal()">
		<button class="accept_button">
			Calcular Total
		</button></a></h3>
	</div>
	<a id="confirma_escolha" href="#" onclick="verificaSeDigitou()">
	<button class="big_button">
		Selecionar
	</button></a>

</div>

app/views/chamados/index.html.erb
<div class="container_secao" >
	<h1>Floricultura Floresbela</h1>
	<table align="center" id="tabela_floriculturistas">
		<tr>
			<th>ID</th>
			<th>Nome do Contratante</th>
			<th>Nome do Falecido</th>
			<th>Telefone de Contato #1</th>
			<th>Telefone de Contato #2</th>
			<th>Endereço do Velório</th>
			<th>Subprefeitura</th>
			<th>Data do Velório</th>
			<th>Itens comprados</th>
			<th>Total</th>
			<th>Aceitar/Recusar</th>
		</tr>

		<% @chamados.each do |chamado| %>
		<tr>
			<td><%= chamado.id %></td>
			<td><%= chamado.nomec %></td>
			<td><%= chamado.nomef %></td>
			<td><%= chamado.telefone1 %></td>
			<td><%= chamado.telefone2 %></td>
			<td><%= chamado.endvel %></td>
			<td><%= chamado.bairro %></td>
			<td><%= chamado.datahorariovel.strftime("%d/%m, %H:%Mh")%></td>
			<td><%= chamado.itens %></td>
			<td>R$<%= chamado.total %></td>
			<td>
			<button class="accept_button">
				Aceitar
			</button>
			<button class="refuse_button">
				Recusar
			</button></td>
		</tr>
		<% end %>
	</table>
</div>

app/views/chamados/new.html.erb
<%= link_to "Log out", logout_path %>
<%= form_for :chamado, url: chamados_path do |f| %>
	<%= render "selecao_produtos" %>
	<div id="separador1" class="separador"></div>
	
	<%= render "cadastro_dados", f: f %>
	<div id="separador2" class="separador"></div>
	<%= render "confirmacao_dados", f: f %>
<% end %>

app/views/chamados/show.html.erb
<div  class="container_secao">
	<%flash.each do |nome, msg|%>
			<%= content_tag :div, msg, id: "flash_#{nome}"%>
		<% end %>
	<div id="box_impressao">
		<h1>Pedido realizado com sucesso!</h1>
		<div id="conferir_dados">
			<a id="confirmacao_floricultura"></a>
			<fieldset class="campo_form">
				<h2>Itens adquiridos</h2>
				<%= @chamado.itens %>
				<h3>Total: R$ <%= @chamado.total %></span></h3>
				<h2>Dados do Contratante</h2>
				<table class="alinhar">
					<tr>
						<td><strong>Nome Completo (Contratante):</strong></td>
						<td> <%= @chamado.nomec %> </td>
					</tr>
					<tr>
						<td><strong>CPF:</strong></td>
						<td> <%= @chamado.cpf %> </td>
					</tr>
					<tr>
						<td><strong>Telefone 1:</strong></td>
						<td> <%= @chamado.telefone1 %> </td>
					</tr>
					<tr>
						<td><strong>Telefone 2:</strong></td>
						<td> <%= @chamado.telefone2 %> </td>
					</tr>
				</table>

				<h2>Dados do Falecido e do Velório</h2>
				<table class="alinhar">
					<tr>
						<td><strong>Nome Completo (Falecido):</strong></td>
						<td> <%= @chamado.nomef %> </td>
					</tr>
					<tr>
						<td><strong>Endereço do Velório:</strong></td>
						<td> <%= @chamado.endvel %> </td>
					</tr>
					<tr>
						<td><strong>Subprefeitura:</strong></td>
						<td> <%= @chamado.subprefeitura %> </td>
					</tr>
					<tr>
						<td><strong>Data e Horário do Velório:</strong></td>
						<td> <%= @chamado.datahorariovel.strftime("%d/%m, %H:%M h") %> </td>
					</tr>
				</table>

				<h2>Dados do Emitente</h2>
				<table class="alinhar">
					<tr>
						<td><strong>Nome Completo (Emitente):</strong></td>
						<td> <%= @chamado.nomee %> </td>
					</tr>
					<tr>
						<td><strong>Forma de pagamento:</strong></td>
						<td> <%= @chamado.formapag %> </td>
					</tr>
				</table>
			</fieldset>
			<a href="../venda">
				<button class="big_button">Novo Chamado</button>
			</a>
			<button class="big_button" onclick="window.print()">Imprimir</button>

		</div>
	</div>
</div>

app/views/floriculturas/new.html.erb
<%= form_for @floricultura do |f| %>	
<table class="alinhar">
			<tr>
				<td><strong>Email *</strong></td>
				<td> <%= f.text_field :email, :required => true %> </td>
			</tr>
			<%= fields_for @usuario do |u|%>
				<tr>
					<td><strong>Senha *</strong></td>
					<td> <%= u.text_field :password, :required => true %></td>
				</tr>
				<tr>
					<td><strong>Confirmar Senha *</strong></td>
					<td> <%= u.text_field :password_confirmation, :required => true  %> </td>
				</tr>
			<% end %>
			<tr>
				<td><strong>Nome da Floricultura</strong></td>
				<td> <%= f.text_field :nomefloricultura, :required => true  %> </td>
			</tr>
			<tr>
				<td><strong>Endereço da Floricultura</strong></td>
				<td> <%= f.text_field :endfloricultura, :required => true  %> </td>
			</tr>
			<tr>
				<td><strong>Bairro *</strong></td>
				<td> <%= f.select :subprefeitura, options_for_select(@bairro.collect { |bairro|
				[bairro.bairro, bairro.subprefeitura] } ), :required => true  %> </td>
			</tr>
			<tr>
				<%= f.hidden_field :tipo, :value => "floricultura" %>
				<td><%= f.submit %></td>
			</tr>
		</table>
		<% end %>

app/views/floriculturas/show.html.erb
<%= link_to "Log out", logout_path %>
<div class="container_secao" >
	<h1><%= @floricultura.nomefloricultura %></h1>
	<table id="tabela_floriculturistas" align="center">
		<tr>
			<th>ID</th>
			<th>Nome do Contratante</th>
			<th>Nome do Falecido</th>
			<th>Telefone de Contato #1</th>
			<th>Telefone de Contato #2</th>
			<th>Endereço do Velório</th>
			<th>Subprefeitura</th>
			<th>Data do Velório</th>
			<th>Itens comprados</th>
			<th>Total</th>
			<th>Tempo até expirar o chamado</th>
			<th>Aceitar/Recusar</th>
		</tr>

		<% @abertos.each do |chamado| %>
		<tr>
			<td><%= chamado.id %></td>
			<td><%= chamado.nomec %></td>
			<td><%= chamado.nomef %></td>
			<td><%= chamado.telefone1 %></td>
			<td><%= chamado.telefone2 %></td>
			<td><%= chamado.endvel %></td>
			<td><%= chamado.subprefeitura %></td>
			<td><%= chamado.datahorariovel.strftime("%d/%m, %H:%Mh")%></td>
			<td><%= chamado.itens %></td>
			<td>R$<%= chamado.total %></td>
			<td>00:00:00</td>
			<td>
			<%=button_to "Aceitar", :controller => :floriculturas, :action => :aceitar, :chamado => chamado.id, :id => @floricultura.id %>
			<%=button_to "Recusar", :controller => :floriculturas, :action => :recusar, :chamado => chamado.id, :id => @floricultura.id %>
			</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/layouts/_footer.html.erb
<!-- div container fecha aqui -->
</div>
</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
	
<head>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<title>Módulo Ceres</title>
</head>
<body>

<div id="container">
	<div id="logo">
		<%= image_tag "logo.png" %>
	</div>
	<!-- A div container é fechada no footer -->

app/views/layouts/application.html.erb
<%= render "layouts/header"%>
<%= yield %>
<%= render "layouts/footer"%>

app/views/usuarios/new.html.erb
<%= form_for @usuario do |f| %>
<% if @usuario.errors.any? %>
	<h2>Ocorreram erros no cadastro:</h2>
	<ul>
		<% @usuario.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<%end%>
	</ul>
	<%end%>
<table class="alinhar">
			<tr>
				<td><strong>Email *</strong></td>
				<td> <%= f.text_field :email, :required => true %> </td>
			</tr>
			<tr>
				<td><strong>Senha *</strong></td>
				<td> <%= f.text_field :password, :required => true %></td>
			</tr>
			<tr>
				<td><strong>Confirmar Senha *</strong></td>
				<td> <%= f.text_field :password_confirmation, :required => true  %> </td>
			</tr>
			<tr>
				<td><strong>Tipo</strong></td>
				<td> <%= f.select :tipo, ([["Agenciador", "agenciador"], ["Floricultura", "floricultura"]]) %> </td>
			</tr>
			
			<tr>
				<td><%= f.submit %></td>
			</tr>
		</table>
		<% end %>